apiVersion: v1
kind: Pod
spec:
  serviceAccountName: jenkins-agent-sa
  nodeSelector:
    dedicated: wsc-cicd
  containers:
    - name: docker
      image: docker:27-cli
      command:
        - sleep
      args:
        - infinity
      env:
        - name: DOCKER_HOST
          value: tcp://localhost:2375

    - name: docker-daemon
      image: docker:27-dind
      securityContext:
        privileged: true
      args:
        - --host=tcp://0.0.0.0:2375
        - --tls=false
      readinessProbe:
        exec:
          command:
            - docker
            - info
        initialDelaySeconds: 3
        periodSeconds: 2
        timeoutSeconds: 2
        failureThreshold: 30

    - name: aws
      image: amazon/aws-cli:latest
      command:
        - sleep
      args:
        - infinity